# Generated by Django 4.2.7 on 2025-05-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
